name: Clang Linux Builds

on:
  # Run every day
  schedule:
    - cron:  '* 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  mainline-clang-11:
    runs-on: ubuntu-latest
    container: tuxbuild/tuxbuild
    env:
      TUXBUILD_TOKEN: ${{ secrets.TUXBUILD_TOKEN }}
    steps:
      - name: mainline-clang-11
        run: tuxbuild build-set --git-repo 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git' --git-ref master --tux-config https://raw.githubusercontent.com/danrue/tuxbuild-demo/main/tuxbuilds.yml --set-name clang-11

  mainline-clang-nightly:
    runs-on: ubuntu-latest
    container: tuxbuild/tuxbuild
    env:
      TUXBUILD_TOKEN: ${{ secrets.TUXBUILD_TOKEN }}
    steps:
      - name: mainline-clang-nightly
        run: tuxbuild build-set --git-repo 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git' --git-ref master --tux-config https://raw.githubusercontent.com/danrue/tuxbuild-demo/main/tuxbuilds.yml --set-name clang-11

  stable:
    runs-on: ubuntu-latest
    container: tuxbuild/tuxbuild
    env:
      TUXBUILD_TOKEN: ${{ secrets.TUXBUILD_TOKEN }}
    steps:
      - name: mainline-clang-nightly
        run: tuxbuild build-set --git-repo 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git' --git-ref master --tux-config https://raw.githubusercontent.com/danrue/tuxbuild-demo/main/tuxbuilds.yml --set-name stable

  #unstable:
  #  runs-on: ubuntu-latest
  #  container: tuxbuild/tuxbuild
  #  env:
  #    TUXBUILD_TOKEN: ${{ secrets.TUXBUILD_TOKEN }}
  #  steps:
  #    - name: mainline-clang-nightly
  #      run: tuxbuild build-set --git-repo 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git' --git-ref master --tux-config https://raw.githubusercontent.com/danrue/tuxbuild-demo/main/tuxbuilds.yml --set-name unstable

  testing:
    runs-on: ubuntu-latest
    container: tuxbuild/tuxbuild
    env:
      TUXBUILD_TOKEN: ${{ secrets.TUXBUILD_TOKEN }}
    steps:
      - name: mainline-clang-nightly
        run: tuxbuild build-set --git-repo 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git' --git-ref master --tux-config https://raw.githubusercontent.com/danrue/tuxbuild-demo/main/tuxbuilds.yml --set-name testing
